settings:
  application:
    # dev开发环境 test测试环境 prod线上环境
    mode: dev
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 服务名称
    name: goCore
    # 端口号
    port: 8000 # 服务端口号
    # api 版本
    apiversion: v1
    readtimeout: 1
    writertimeout: 2
    # 数据权限功能开关
    enabledp: false
  logger:
    # 日志存放路径
    path: temp/logs
    # 控制台日志
    stdout: true
    # 日志等级
    level: all
    # 业务日志开关
    enabledbus: true
    # 请求日志开关
    enabledreq: false
    # 数据库日志开关 dev模式，将自动开启
    enableddb: true
    # 自动任务日志开关 dev模式，将自动开启
    enabledjob: false
  jwt:
    # token 密钥，生产环境时及的修改
    secret: go-core
    # token 过期时间 单位：秒
    timeout: 3600
    # token 缓冲时间，当 Token 过期且小于缓冲时间时，无需登录，生成新的 Token 单位：秒
    bufferTime: 3600
    # Token 前后端 Header 入参名称
    headerName: Authorization
  mysql:
    # 用户名
    username: root
    # 用户密码
    password: huazi123
    # host
    host: 127.0.0.1
    # 端口
    port: 3306
    # 数据库
    dbname: gocore
    # 配置信息
    config: charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  redis:
    # host
    host: 127.0.0.1
    # 端口
    port: 6379
    # 密码
    password: 
    # 数据库
    db: 0
